import type { Project } from '../types'

// ── Footprint emission factors (DEFRA 2024) ───────────────────────────────────
export const FOOTPRINT_FACTORS = {
  flight: {
    domestic:      0.255,  // tCO2e per flight-hour
    shortHaul:     0.195,
    longHaul:      0.195,
  },
  car: {
    petrol:        0.170,  // tCO2e per 1000 km
    diesel:        0.163,
    electric:      0.053,
    hybrid:        0.120,
  },
  homeEnergy: {
    perUnit:       0.000233, // tCO2e per kWh
  },
  diet: {
    vegan:         1.5,    // tCO2e per year
    vegetarian:    1.7,
    omnivore:      2.5,
    highMeat:      3.3,
  },
} as const

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    slug: 'ahmedabad-urban-canopy',
    name: 'Ahmedabad Urban Canopy',
    element: 'earth',
    category: 'Afforestation & Land',
    location: 'Ahmedabad, Gujarat',
    country: 'India',
    partner: 'Green Cities India',
    certification: 'Gold Standard',
    certificationId: 'GS-2024-001',
    pricePerTree: 120,
    totalTrees: 5000,
    fundedTrees: 2800,
    fundersCount: 142,
    lastEvidenceDate: '2024-07-15',
    evidenceCount: 8,
    tCO2e: 47.6,
    description: 'Planting native tree species across urban parks and road medians in Ahmedabad to reduce heat island effect and improve air quality.',
    verified: true,
    status: 'active',
    createdAt: '2024-01-10T00:00:00Z',
    coverImage: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop',
  },
  {
    id: '2',
    slug: 'bhopal-community-grove',
    name: 'Bhopal Community Grove',
    element: 'earth',
    category: 'Community Forestry',
    location: 'Bhopal, Madhya Pradesh',
    country: 'India',
    partner: 'Madhya Pradesh Forest Dept.',
    certification: 'Verra VCS',
    certificationId: 'VCS-2024-042',
    pricePerTree: 95,
    totalTrees: 8000,
    fundedTrees: 3100,
    fundersCount: 89,
    lastEvidenceDate: '2024-06-20',
    evidenceCount: 5,
    tCO2e: 52.7,
    description: 'Community-managed grove restoration on degraded land, providing livelihoods for 200 families while sequestering carbon.',
    verified: true,
    status: 'active',
    createdAt: '2024-02-05T00:00:00Z',
    coverImage: 'https://images.unsplash.com/photo-1542601906897-ecd3f4e5c1a3?w=600&auto=format&fit=crop',
  },
  {
    id: '3',
    slug: 'nilgiris-shola-restoration',
    name: 'Nilgiris Shola Restoration',
    element: 'earth',
    category: 'Ecosystem Restoration',
    location: 'Nilgiris, Tamil Nadu',
    country: 'India',
    partner: 'Keystone Foundation',
    certification: 'Plan Vivo',
    certificationId: 'PV-2023-018',
    pricePerTree: 140,
    totalTrees: 3000,
    fundedTrees: 2650,
    fundersCount: 211,
    lastEvidenceDate: '2024-07-01',
    evidenceCount: 12,
    tCO2e: 45.1,
    description: 'Restoring endangered shola grassland-forest mosaic in the Nilgiri Biosphere Reserve, protecting endemic species and water catchments.',
    verified: true,
    status: 'active',
    createdAt: '2023-11-20T00:00:00Z',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&auto=format&fit=crop',
  },
  {
    id: '4',
    slug: 'sundarbans-mangrove',
    name: 'Sundarbans Mangrove Belt',
    element: 'earth',
    category: 'Mangrove Restoration',
    location: 'Sundarbans, West Bengal',
    country: 'India',
    partner: 'Sundarbans Biosphere Trust',
    certification: 'Gold Standard',
    certificationId: 'GS-2024-077',
    pricePerTree: 110,
    totalTrees: 10000,
    fundedTrees: 4200,
    fundersCount: 178,
    lastEvidenceDate: '2024-05-30',
    evidenceCount: 6,
    tCO2e: 71.4,
    description: 'Replanting mangrove forests along the Sundarbans coastline to protect communities from cyclones and restore critical tiger habitat.',
    verified: true,
    status: 'active',
    createdAt: '2024-03-01T00:00:00Z',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop',
  },
  {
    id: '5',
    slug: 'aravalli-slope-greening',
    name: 'Aravalli Slope Greening',
    element: 'earth',
    category: 'Dryland Restoration',
    location: 'Alwar, Rajasthan',
    country: 'India',
    partner: 'Tarun Bharat Sangh',
    certification: 'Verra VCS',
    certificationId: 'VCS-2024-091',
    pricePerTree: 80,
    totalTrees: 15000,
    fundedTrees: 6800,
    fundersCount: 95,
    lastEvidenceDate: '2024-06-10',
    evidenceCount: 4,
    tCO2e: 115.6,
    description: 'Revegetating degraded Aravalli hill slopes with drought-resistant native species, restoring groundwater recharge and preventing soil erosion.',
    verified: false,
    status: 'active',
    createdAt: '2024-04-15T00:00:00Z',
    coverImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&auto=format&fit=crop',
  },
  {
    id: '6',
    slug: 'kerala-agroforestry',
    name: 'Kerala Agroforestry Network',
    element: 'earth',
    category: 'Agroforestry',
    location: 'Wayanad, Kerala',
    country: 'India',
    partner: 'Wayanad Farmers Collective',
    certification: 'Plan Vivo',
    certificationId: 'PV-2024-033',
    pricePerTree: 100,
    totalTrees: 6000,
    fundedTrees: 1800,
    fundersCount: 63,
    lastEvidenceDate: '2024-07-08',
    evidenceCount: 3,
    tCO2e: 30.6,
    description: 'Integrating native trees into smallholder coffee and spice farms in Wayanad, boosting biodiversity and farmer incomes while sequestering carbon.',
    verified: true,
    status: 'active',
    createdAt: '2024-05-20T00:00:00Z',
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop',
  },
]